apiVersion: v1
kind: Service
metadata:
  name: consumer
  namespace: resume-demo
spec:
  selector:
    app: consumer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP

