apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-service
  template:
    metadata:
      labels:
        app: consumer-service
    spec:
      containers:
        - name: consumer-service
          image: consumer-service:local
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_QUEUE
              value: resume.events
            - name: ASPNETCORE_URLS
              value: http://+:8080
          ports:
            - containerPort: 8080
